# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'PeopleDailys' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PeopleDailys
pod 'AFNetworking'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'Masonry'

end
